### PR TITLE
1-generic-error-when-receiving-list-of-users

### LINKED ISSUE #1: As Client I want to get a list of all Users
Description
A client can receive a list of users 

Example

*Happy path:*
Request: GET /api/users/list

Response: 200 OK

{ id:'1' , id:'2' , id:'3' }

*In case there are no users*
Request: GET /api/users/list

Response: 200 OK

[]

*Generic error:*
Request: GET /api/users/list

Response: 400 Bad Response

{ 'error': 'An error occured while a petition was made' }

### PR DESCRIPTION
**Pull request by AMBuilds**
First Pull Request. If something is wrongly made, let me know.

### CODE REVIEW

File: tests/app/Infrastructure/Controller/GetUsersListControllerTest.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    /**
+     * @setUp
+     */
+    protected function setUp(): void
+    {
+        parent::setUp();
+
+        $this->userDataSource = Mockery::mock(UserDataSource::class);
+        $this->app->bind(UserDataSource::class, fn () => $this->userDataSource);
+
```
Comment (rubeniriso) [inline tests/app/Infrastructure/Controller/GetUsersListControllerTest.php]: newline unnecessary

**Review by rubeniriso — CHANGES_REQUESTED** [review]
A bit of formatting

**Review by rubeniriso — APPROVED** [review]
